### ISSUE TITLE
Error in latest version

### ISSUE THREAD

**Issue by mohsinalimat** [xnth97/AccessoryKit#1]
Hello,

Error in the latest version

![Screenshot 2021-01-13 at 2 04 31 PM](https://user-images.githubusercontent.com/973676/104426785-65758780-55a8-11eb-8627-97d813d6fca0.png)

**Comment by xnth97** [comment]
Hi,

Thanks for your feedback. Which Xcode version are you using? The newly introduced UIMenu support requires iOS 14 SDK hence Xcode 12 is also required.

**Comment by mohsinalimat** [comment]
Ok.
