### ISSUE TITLE
Accessory view click function implementation  

### ISSUE THREAD

**Issue by ArunVicky001** [xnth97/AccessoryKit#2]
Hi @xnth97 

Thanks for this library.  Could you please suggest how to implement the function for the Accessory view button. why dont you add those functionality as well in the prototype. 

Thank you.

**Comment by xnth97** [comment]
hi @ArunVicky001 

i'm not sure if i follow your question. if you meant the tap handlers for buttons, it is indeed in the example and readme doc

https://github.com/xnth97/AccessoryKit/blob/30f76ab862703a77458c214196050ce59b657391/Example/AccessoryKit/ViewController.swift#L22

**Comment by ArunVicky001** [comment]
Hi @xnth97 I got this, I was trying to set the selected text to bold 
```
KeyboardAccessoryButton(identifier: "bold", type: .bold , position: .leading) { [weak self] in
                self?.bold()
            }
```
private func bold() {
        
}

do you have any workaround/style class to change the selected text to be bold/italic etc..  or do we need to do the rest of styling like for these items?  
       ```
 case bold
        case italic
        case code
        case delete
        case item
        case quote
        case link
        case image

```

**Comment by xnth97** [comment]
@ArunVicky001 that is out of this library's scope. AccessoryKit only provides input accessory view and is not coupled with any rich text functionality
